# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/design_1_system_ila_2_1.xci
# IP: The module: 'design_1_system_ila_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/bd_f66c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f66c || ORIG_REF_NAME==bd_f66c} -quiet] -quiet

# IP: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/bd_f66c_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/bd_f66c_ila_lib_0_ooc.xdc

# XDC: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/bd_f66c_ooc.xdc

# XDC: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/design_1_system_ila_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_2_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/design_1_system_ila_2_1.xci
# IP: The module: 'design_1_system_ila_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/bd_f66c.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f66c || ORIG_REF_NAME==bd_f66c} -quiet] -quiet

# IP: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/bd_f66c_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/bd_f66c_ila_lib_0_ooc.xdc

# XDC: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/bd_f66c_ooc.xdc

# XDC: c:/Users/willylin/Desktop/dp_ver3/dp_ver3/dp-ver3.gen/sources_1/bd/design_1/ip/design_1_system_ila_2_1/design_1_system_ila_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
