@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri May 27 11:48:46 +0800 2022
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 95d263053d4b4dcfa82f10f8e2caa522 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_13 -L axi_lite_ipif_v3_0_4 -L v_tc_v6_1_13 -L v_vid_in_axi4s_v4_0_9 -L v_axi4s_vid_out_v4_0_12 -L v_tc_v6_2_2 -L v_tpg_v8_1_2 -L xlconcat_v2_1_4 -L xlconstant_v1_1_7 -L axi_infrastructure_v1_1_0 -L axi_vip_v1_1_10 -L zynq_ultra_ps_e_vip_v1_0_10 -L gigantic_mux -L generic_baseblocks_v2_1_0 -L fifo_generator_v13_2_5 -L axi_data_fifo_v2_1_23 -L axi_register_slice_v2_1_24 -L axi_protocol_converter_v2_1_24 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot test_bench_behav xil_defaultlib.test_bench xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 95d263053d4b4dcfa82f10f8e2caa522 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_13 -L axi_lite_ipif_v3_0_4 -L v_tc_v6_1_13 -L v_vid_in_axi4s_v4_0_9 -L v_axi4s_vid_out_v4_0_12 -L v_tc_v6_2_2 -L v_tpg_v8_1_2 -L xlconcat_v2_1_4 -L xlconstant_v1_1_7 -L axi_infrastructure_v1_1_0 -L axi_vip_v1_1_10 -L zynq_ultra_ps_e_vip_v1_0_10 -L gigantic_mux -L generic_baseblocks_v2_1_0 -L fifo_generator_v13_2_5 -L axi_data_fifo_v2_1_23 -L axi_register_slice_v2_1_24 -L axi_protocol_converter_v2_1_24 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot test_bench_behav xil_defaultlib.test_bench xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
